language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-20.0.0

    # The SDK version used to compile your project
    - android-16

    - sys-img-armeabi-v7a-android-16
    - sys-img-x86-android-16
before_install:
  - echo no | android create avd -c 50M --force -n testarm -t android-16 --abi armeabi-v7a
  - echo no | android create avd -c 50M --force -n textx86 -t android-16 --abi x86
  - emulator -avd testarm -no-skin -no-audio -no-window &
  - emulator -avd testx86 -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build