language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-20.0.0

    # The SDK version used to compile your project
    - android-16

    - sys-img-x86-android-16
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-l
    - sys-img-x86-android-l

script:
  - ./runTests.sh || exit 1
